### ISSUE TITLE
DJANGO SECRET KEY 

### ISSUE THREAD

**Issue by eddapp** [mehhran/rfid-tag-django-api#1]
from tagsProject.secrets import DJANGO_SECRET_KEY
ModuleNotFoundError: No module named 'tagsProject.secrets'

**Comment by eddapp** [comment]
this is pointing to a file that does no exist. I just removed the line of code calling this at the top of the settings.py file. I then put the secret key in "" so that it would set the secret key and compile properly to run the server. please advise in readme for further use of the file or how to assign the secret key to the file being ref etc not too sure

**Comment by mehhran** [comment]
@eddapp Thank you for your input
Just updated the README and settings.py
Please check again and give me your feedback

**Comment by eddapp** [comment]
@mehhran ty for the response and the update as it is working now. What are you using as the reader for the tags etc. I am looking to hook up some raspberry pi for like a library check out reader by the door. maybe pm me :)

**Comment by mehhran** [comment]
@eddapp I am using an android device, [CF-RU6508](http://www.chafon.com/productdetails.aspx?pid=673), with a couple of [antennas](http://www.chafon.com/product.aspx?cid=253) attached to it. It has an SDK in Java that I've used in [rfid-tag-manager-android](https://github.com/mehhran/rfid-tag-manager-android).
